name: 'Spam Check'
author: 'apoorvd14@gmail.com'
description: 'Spam Check helps you to filter out spam PRs in your repository.'
branding:
  icon: 'info'
  color: 'green'
inputs:
  OPENAI_API_KEY:
    description: 'OpenAI API Key'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  GITHUB_REPOSITORY:
    description: 'GitHub Repository'
    required: true
  PR_NUMBER:
    description: 'Pull Request Number'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    GITHUB_REPOSITORY: ${{ inputs.GITHUB_REPOSITORY }}
    PR_NUMBER: ${{ inputs.PR_NUMBER }}