name: Spam Check Workflow

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  spam-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Spam Checker
        uses: apoorvdwi/spam-check@v3.0
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          MAX_FILES: 5
          FILES_TO_EXCLUDE: ''
          USE_GPT4: false
